### ISSUE TITLE
Add to brew

### ISSUE THREAD

**Issue by alice0meta** [harto/realpath-osx#7]
It'd be useful to have this in http://brew.sh/, like `brew install realpath-osx`

**Comment by harto** [comment]
I think GNU realpath might be included via the `coreutils` formula. That might be easier (and undoubtedly better-written, tested, etc...) :-)

**Comment by harto** [comment]
Added a note to README in 1406b23651e81de1b6025843ca490d48c56b320d.

**Comment by amaramth** [comment]
Thanks for the tip! Sorry I keep bothering you :)

**Comment by harto** [comment]
No problem! I actually wasn't aware of the formula until I looked just now, so thanks for prompting me :-)

**Comment by vladimyr** [comment]
@harto Are you open to creating/owning a private homebrew tap? Let me know if you are interested and I can create one and transfer it to you. End result would be:
```sh
brew tap harto/tap
brew install realpath-osx
```

**Comment by harto** [comment]
I don't think so... I don't really want to offer a guarantee that this works correctly or that I'm going to maintain it long-term. If anyone wants to fork this project and maintain it for Homebrew I'm totally fine with that.

**Comment by vladimyr** [comment]
Well thanks for thinking about it and letting me know 👍

**Comment by harto** [comment]
No worries! Thanks for offering to set up the tap.
