### ISSUE TITLE
this answer seems to work on linux

### ISSUE THREAD

**Issue by ORESoftware** [harto/realpath-osx#8]
this code:

https://stackoverflow.com/a/46772980/1223975

I compiled on Ubuntu with gcc and it works. I assume it would work on MacOS too

**Comment by harto** [comment]
Yeah, there are many ways to do this on OSX. My recommendation is in this project's README:
> If you want a "real" implementation of this command, the GNU version is available via the coreutils Homebrew formula:
>
>     brew install coreutils

**Comment by ORESoftware** [comment]
thanks do you know if coreutils will mess up anything that already exists on MacOS?

**Comment by harto** [comment]
As far as I'm aware the coreutils binaries are prefixed with `g` (`grealpath`, etc.) so they won't conflict with OS X system binaries.

**Comment by ORESoftware** [comment]
nice that's cool, I might try that out
